name: DNAseq_references
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::bcftools=1.9
  - bioconda::bedtools=2.28.0
  - bioconda::bwa=0.7.17
  - bioconda::gatk4=4.1.2.0
  - bioconda::picard=2.20.3
  - bioconda::samtools=1.9
  - bioconda::ensembl-vep=99.2
  - conda-forge::google-cloud-sdk<243.0.0
  - conda-forge::python=2.7.15
